Repository zonemaster/zonemaster-engine, pull requests merged in 2020-09, with the labels that each got.

#777 Fix NO_SOA_IN_RESPONSE message
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: A-TestCase, T-Bug

#770 Reduce duplicate messages about key size
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-TestCase

#762 - Add method name (test case) in Logger.
  lib/Zonemaster/Engine/Logger.pm
  lib/Zonemaster/Engine/Logger/Entry.pm
  t/logger.t
Labels: A-TestCase

#775 Implement singleton pattern idiomatically
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/Engine/Translator.pm
Labels: A-Translation

#776 Validate use of arguments in translated messages
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  share/Makefile
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
  util/check-msg-args
Labels: A-Translation

#781 Revert "Fix NO_SOA_IN_RESPONSE message"
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: P-High

#782 "Fix NO_SOA_IN_RESPONSE message" to correct branch
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: A-Translation, T-Bug

#784 Silence PACKET_BIG for the time being
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Translator.pm
  share/profile.json
  share/profile_example_logfilter.json
  t/profiles/Test-all-levels.json
Labels: A-Code

#768 Added references to specific files for test case lists in Profile.pm
  lib/Zonemaster/Engine/Profile.pm
Labels: A-Documentation

#772 Updated instructions for translators
  docs/Translation-translators.md
  docs/Translation.pod
Labels: A-Translation

#786 Norwegian language fix after reveiw
  share/nb.po
Labels: A-Translation, P-High

#787 Add missing dots at the end of several msgid
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
Labels: A-TestCase, P-High

#794 Rename message argument to match source
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-Translation, P-High

#792 Update ns args in SYSTEM messages
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Translator.pm
  lib/Zonemaster/Engine/Zone.pm
Labels: A-Code

#795 msgid in English
  lib/Zonemaster/Engine/Test/Connectivity.pm
Labels: A-Translation

#796 Update message argument names in PO files
  share/Makefile
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-Translation, P-High
