Repository zonemaster/zonemaster-engine, pull requests merged in 2020-07, with the labels that each got.

#752 Remove workaround for previously unsupported C locale
  lib/Zonemaster/Engine/Translator.pm
Labels: A-Translation, S-ProposalExists

#759 Fix implementation of Consistency/consistency05
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Util.pm
  t/Test-consistency05-K.data
  t/Test-consistency05-K.t
  t/Test-consistency05-L.t
Labels: A-TestCase

#760 Fixes messages in Delegation/delegation01
  lib/Zonemaster/Engine/Test/Delegation.pm
Labels: A-TestCase

#758 DNSSEC module MsgID missing + MsgID Typo Fixed
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/fr.po
Labels: A-Translation

#761 - Fixes French translation
  share/fr.po
Labels: A-Translation

#765 Remove deleted Test-disabled.json
  MANIFEST
Labels: A-Code, T-Bug

#767 Remove MODULE_CALL and MODULE_CALL_END messages
  lib/Zonemaster/Engine/Test.pm
Labels: A-TestCase

#764 Add START/END messages in case of debug of test cases
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Syntax.pm
  lib/Zonemaster/Engine/Test/Zone.pm
  share/profile.json
  t/Test-address.t
  t/Test-dnssec.t
  t/old-bugs.t
Labels: A-TestCase
