Repository zonemaster/zonemaster-engine, pull requests merged in 2020-05, with the labels that each got.

#728 Remove empty elements from @keys to resolve issue #727
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-TestCase

#729 Preparation for fix release v2019.2.1 (Engine v3.1.1)
  Changes
  lib/Zonemaster/Engine.pm
Labels: A-Code, A-Documentation

#733 Merge Develop into Master for v2019.2.1 (Zonemaster-Engine)
  Changes
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-BuildSystem

#737 - Fixes case issue when comparing domain name in Zone10
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: A-TestCase

#740 Preparation for release v2019.2.2 (Zonemaster-Engine v3.1.2)
  Changes
  lib/Zonemaster/Engine.pm
Labels: A-BuildSystem

#741 Merge Develop into Master for v2019.2.2 (Zonemaster-Engine)
  Changes
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: A-BuildSystem

#726 Updates to translation tooling
  .gitignore
  MANIFEST.SKIP
  docs/Translation.pod
  share/Makefile
Labels: A-Translation, S-ProposalExists

#689 Add Zonemaster::Net::IP::ip_is_ipv4
  lib/Zonemaster/Engine/Net/IP.pm
Labels: A-Code

#736 Remove the DISABLED feature
  docs/ConfigAndPolicy.pod
  docs/Installation.md
  lib/Zonemaster/Engine/Test.pm
  lib/Zonemaster/Engine/Translator.pm
  share/profile.json
  share/profile_example_logfilter.json
  t/profiles/Test-all-levels.json
  t/profiles/Test-disabled.json
  t/zonemaster.t
Labels: A-Code

#725 Update fr.po
  share/fr.po
Labels: A-Translation
