Repository zonemaster/zonemaster-engine, pull requests merged in 2020-12, with the labels that each got.

#803 change syntax06 according to the last revision of specs.
  lib/Zonemaster/Engine/Test/Syntax.pm
  t/Test-dnssec.data
  t/Test-syntax.data
  t/Test-syntax06-A.data
  t/Test-syntax06-A.t
  t/Test-syntax06-E.data
  t/Test-syntax06-E.t
  t/Test-syntax06-F.data
  t/Test-syntax06-F.t
  t/Test-syntax06-G.data
  t/Test-syntax06-G.t
  t/Test-syntax06-I.data
  t/Test-syntax06-I.t
  t/Test-syntax06-J.data
  t/Test-syntax06-J.t
  t/Test-syntax06-K.data
  t/Test-syntax06-K.t
  t/Test-syntax06-L.data
  t/Test-syntax06-L.t
Labels: A-TestCase, P-High

#854 Naming of domain message args
  docs/logentry_args.md
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Test.pm
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Syntax.pm
  lib/Zonemaster/Engine/Translator.pm
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-Translation

#846 - Missing spaces in message
  lib/Zonemaster/Engine/Test/Consistency.pm
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-TestCase, A-Translation
