Repository zonemaster/zonemaster-engine, pull requests merged in 2020-11, with the labels that each got.

#824 Translation update (Danish)
  share/da.po
Labels: A-Translation, P-High

#832 Corrected sv.po
  share/sv.po
Labels: A-Translation

#836 For release v2020.1 (Engine)
  Changes
  Makefile.PL
  README.md
  lib/Zonemaster/Engine.pm
Labels: P-High

#838 Updated due to incorrect version number specification (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High

#839 Merge develop into master (Engine), second time
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High

#834 Fixed riswhois (RIPE) support
  lib/Zonemaster/Engine/ASNLookup.pm
Labels: A-TestCase, T-Bug

#841 Updates for release v2020.1.1
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#842 Merge develop into master (Engine)
  Changes
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/ASNLookup.pm
Labels: P-High

#847 Updates for v2020.1.2 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#848 Merge develop into master (Engine)
  Changes
  lib/Zonemaster/Engine.pm
  t/Test-dnssec.data
Labels: P-High

#849 Root hint data updated
  lib/Zonemaster/Engine/Recursor.pm
  t/Test-syntax.data
  t/Test-zone.data
Labels: A-Code

#852 Changed numeric sorting to lexically resolving issue #851
  lib/Zonemaster/Engine/Test/Connectivity.pm
Labels: A-TestCase

#843 Remove unused config_example_logfilter.json
  MANIFEST
  share/config_example_logfilter.json
Labels: A-Code

#853 Naming of message args
  docs/logentry_args.md
  lib/Zonemaster/Engine/Test.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Translator.pm
  share/da.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-Translation
