Repository zonemaster/zonemaster-engine, pull requests merged in 2020-04, with the labels that each got.

#700 Remove useless dependency
  .travis.yml
  lib/Zonemaster/Engine/Test.pm
Labels: A-Code

#701 Updated and expanded Translation document
  docs/Translation.pod
Labels: A-Translation

#698 French translations updated
  share/fr.po
Labels: A-Translation, S-ProposalExists

#709 Update supported Perl versions in Travis
  .travis.yml
Labels: A-Travis

#708 Clarified the instructions for the translators
  docs/Translation.pod
Labels: A-Translation

#666 Updates in prepartion for release v2019.2
  Changes
Labels: P-High

#710 Updated Swedish translation (sv.po)
  share/sv.po
Labels: A-Translation

#716 Added translation for new message
  share/sv.po
Labels: A-Translation, S-ProposalExists

#718 Update da.po 20200422
  share/da.po
Labels: A-Translation

#690 Update FreeBSD installation steps
  docs/Installation.md
Labels: A-Installation, S-ProposalExists, T-Bug

#683 Updated CentOS Install Instruction
  docs/Installation.md
Labels: A-Installation

#723 Preperations for release v2019.2
  Changes
  lib/Zonemaster/Engine.pm
Labels: A-Code, A-Documentation
