Repository zonemaster/zonemaster-engine, pull requests merged in 2020-10, with the labels that each got.

#801 Adding missing file to MANIFEST
  MANIFEST
Labels: A-BuildSystem, P-High

#799 Rename more message args
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
Labels: A-TestCase

#802 Update of Connectivity/connectivity03
  lib/Zonemaster/Engine/ASNLookup.pm
  lib/Zonemaster/Engine/Profile.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  share/profile.json
  share/profile_example_logfilter.json
  t/Test-connectivity.t
  t/Test-dnssec.data
  t/asn.t
  t/profiles.t
  t/profiles/Test-all-levels.json
Labels: A-TestCase

#805 Fix locale initialization
  lib/Zonemaster/Engine/Translator.pm
  share/Makefile
Labels: A-Code, P-High

#807 Remove path from find output i share/Makefile
  share/Makefile
Labels: A-BuildSystem, T-Bug

#806 Updated translations with changed parameters, texts etc.
  share/nb.po
Labels: A-Translation, P-High

#814 Fix installation on CentOS 7
  docs/Translation-translators.md
  share/Makefile
Labels: A-BuildSystem

#811 - Add french translation.
  share/fr.po
Labels: A-Translation, P-High

#815 Use gmake for FreeBSD
  MANIFEST
  Makefile.PL
  docs/Installation.md
Labels: A-BuildSystem, P-High

#819 Use gmake with Freebsd in po-files.t
  t/po-files.t
Labels: A-UnitTests, T-Bug

#823 Translate msgid into Swedish
  share/sv.po
Labels: A-Translation, P-High
