Repository zonemaster/zonemaster-engine, pull requests merged in 2021-09, with the labels that each got.

#954 Backport fix of zonemaster/zonemaster-engine#948
  lib/Zonemaster/Engine/Test/Basic.pm
Labels: P-High

#955 Updates for v2021.1.3 release
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#950 Small translation fix
  share/nb.po
Labels: A-Translation

#958 Backports "replace signature verification function"
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug, P-High

#960 Preparation for fix release v2021.1.3
  Changes
Labels: P-High

#961 Merge fix-release-v2021.1.3 into master (Engine)
  Changes
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: P-High

#957 - Replace signature verification function in DNSSEC16/DNSSEC17
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug

#963 Updates Changes and Engine.pm with updates for release v2021.1.3 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High
