Repository zonemaster/zonemaster-engine, pull requests merged in 2021-01, with the labels that each got.

#860 Add new feature in Profiles to customize some variables values
  lib/Zonemaster/Engine/Profile.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/profile_example_logfilter.json
  t/Test-dnssec.data
  t/Test-dnssec.t
Labels: A-TestCase

#861 Adjusted to supported OS versions
  docs/Installation.md
Labels: A-Installation, P-High

#864 Fix dnssec issues
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  t/Test-dnssec.data
  t/Test-dnssec.t
Labels: A-TestCase, A-UnitTests, S-ProposalExists, T-Bug

#867 Rename profile_example_logfilter.json into profile_example.json
  docs/Profiles.md
  share/profile_example.json
Labels: A-Code
