Repository zonemaster/zonemaster-engine, pull requests merged in 2021-12, with the labels that each got.

#1018 Clean up obsolete documentation
  MANIFEST
  docs/ConfigAndPolicy.pod
Labels: A-Documentation

#1015 Update the translation to French (Engine)
  share/fr.po
Labels: A-Translation

#1022 exclude debian files from manifest
  MANIFEST.SKIP
Labels: P-High

#1023 Preparation for release v2021.2 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High, A-Documentation

#1011 Updates the translation to Swedish (Engine)
  share/sv.po
Labels: A-Translation

#1026 Updated the Norwegian language translation
  share/nb.po
Labels: A-Translation

#1025 Update danish translation
  share/da.po
Labels: A-Translation

#994 New translation to spanish language.
  MANIFEST
  share/es.po
Labels: A-Translation

#1030 Preparation for v2021.2.1 release (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#1031 Merge develop into master (Engine)
  Changes
  MANIFEST
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/da.po
  share/es.po
  share/nb.po
  share/sv.po
Labels: P-High
