Repository zonemaster/zonemaster-engine, pull requests merged in 2021-05, with the labels that each got.

#892 Implementation of Basic04
  lib/Zonemaster/Engine/Test/Basic.pm
  share/profile.json
  share/profile_example.json
  t/Test-basic.data
  t/Test-basic.t
  t/profiles/Test-all.json
  t/profiles/Test-basic-all.json
Labels: A-TestCase, FA-Basic04

#901 Adds missing file to MANIFEST (zonemaster-engine)
  MANIFEST
Labels: P-High

#900 DNSSEC16 test case implementation
  MANIFEST
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/profile.json
  share/profile_example.json
  t/Test-dnssec.data
  t/Test-dnssec.t
  t/profiles/Test-dnssec-all.json
  t/profiles/Test-dnssec16-only.json
Labels: FA-CDS-CDNSKEY

#915 Corrects two typos in DNSSEC.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug

#916 Update of Swedish translation
  share/sv.po
Labels: A-Translation, P-High

#917 Add french translations
  share/fr.po
Labels: A-Translation, P-High

#921 Missing circumflex diacritic
  share/fr.po
Labels: A-Translation

#918 Remove installation instruction for FreeBSD 11
  docs/Installation.md
Labels: A-Documentation, P-High

#923 Update profile to reduce repeated messages on no response
  share/profile.json
  share/profile_example.json
Labels: A-TestCase, FA-Basic04, P-High

#926 Update CentOS installation instruction
  docs/Installation.md
Labels: P-High

#925 Danish translation update
  share/da.po
Labels: A-Translation, P-High

#927 Updated Norwegian translation and added translation to new messages
  share/nb.po
Labels: A-Translation, P-High

#924 Prepares for release of v2021.1 (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High
