Repository zonemaster/zonemaster-engine, pull requests merged in 2021-02, with the labels that each got.

#870 Fixes incorrect parameter names in call
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-TestCase, T-Bug

#872 Updates some msgstr for Swedish
  share/sv.po
Labels: A-Translation, P-High

#874 Fix issue zonemaster engine 873
  share/fr.po
Labels: A-Translation, P-High

#875 Prepares for release v2020.2 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: A-Code, A-Documentation, P-High

#876 Merge develop into master (Engine)
  Changes
  MANIFEST
  docs/Installation.md
  docs/Profiles.md
  docs/logentry_args.md
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Profile.pm
  lib/Zonemaster/Engine/Recursor.pm
  lib/Zonemaster/Engine/Test.pm
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Syntax.pm
  lib/Zonemaster/Engine/Translator.pm
  share/config_example_logfilter.json
  share/da.po
  share/fr.po
  share/nb.po
  share/profile.json
  share/profile_example.json
  share/sv.po
  t/Test-dnssec.data
  t/Test-dnssec.t
  t/Test-syntax.data
  t/Test-syntax06-A.data
  t/Test-syntax06-A.t
  t/Test-syntax06-E.data
  t/Test-syntax06-E.t
  t/Test-syntax06-F.data
  t/Test-syntax06-F.t
  t/Test-syntax06-G.data
  t/Test-syntax06-G.t
  t/Test-syntax06-I.data
  t/Test-syntax06-I.t
  t/Test-syntax06-J.data
  t/Test-syntax06-J.t
  t/Test-syntax06-K.data
  t/Test-syntax06-K.t
  t/Test-syntax06-L.data
  t/Test-syntax06-L.t
  t/Test-zone.data
Labels: P-High
