Repository zonemaster/zonemaster-engine, pull requests merged in 2021-11, with the labels that each got.

#999 Removes Locale::Msgfmt from dependency list. Is not a dependency.
  Makefile.PL
  docs/Installation.md
Labels: P-High

#996 update installation doc
  docs/Installation.md
  docs/Translation-translators.md
Labels: P-High, A-Documentation

#997 Updates logentry_args.md
  docs/logentry_args.md
Labels: A-TestCase, A-Documentation

#1012 Updates installation document especially with Docker informatio
  docs/Installation.md
Labels: P-High, A-Documentation

#1009 Removes moved translator instruction
  docs/Translation-translators.md
  docs/Translation.pod
Labels: A-Documentation

#1002 Updates README
  README.md
Labels: P-High, A-Documentation

#1019 fix manifest test
  t/manifest.t
Labels: T-Bug

#1020 Add missing short descr for Nameserver test cases
  lib/Zonemaster/Engine/Test/Nameserver.pm
Labels: T-Bug, A-Documentation
