Repository zonemaster/zonemaster-engine, pull requests merged in 2022-11, with the labels that each got.

#1143 Implement testcase rewrite: Connectivity01 and Connectivity02 + remove Basic04
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  share/profile.json
  t/Test-connectivity.data
  t/Test-connectivity.t
  t/profiles/Test-all.json
  t/profiles/Test-basic-all.json
Labels: A-TestCase, V-Minor

#1144 Add test case description in Engine
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Syntax.pm
  lib/Zonemaster/Engine/Test/Zone.pm
  lib/Zonemaster/Engine/Translator.pm
Labels: V-Minor

#1040 add new basic00 implementation
  MANIFEST
  lib/Zonemaster/Engine/Normalization.pm
  lib/Zonemaster/Engine/Normalization/Error.pm
  t/normalization.t
Labels: V-Minor

#1151 expose the init methods
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Recursor.pm
Labels: P-High, V-Patch

#1152 Corrects the license statement in Engine.pm
  README.md
  lib/Zonemaster/Engine.pm
Labels: A-Documentation

#1157 normalization.t: Avoid non-ASCII characters in test names and notes
  t/normalization.t
Labels: T-Bug
