Repository zonemaster/zonemaster-engine, pull requests merged in 2022-04, with the labels that each got.

#1027 "Fix" dnssec07 profile.json list order
  share/profile.json
  share/profile_example.json
Labels: T-Question

#1037 - Fix dnssec10 case when there are DNSKEY empty lists
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug, A-TestCase

#1047 Corrects argument name in Delegation.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
Labels: T-Bug, A-TestCase

#1010 Fixes typo
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug
