Repository zonemaster/zonemaster-engine, pull requests merged in 2022-12, with the labels that each got.

#1034 New implementation of Nameserver11 - #1110
  lib/Zonemaster/Engine/Test/Nameserver.pm
  share/profile.json
  t/Test-nameserver.data
  t/Test-nameserver.t
Labels: A-TestCase, V-Minor

#1035 Update implementation of Zone01 - #1028
  lib/Zonemaster/Engine/Test/Zone.pm
  share/profile.json
  t/Test-zone.data
  t/Test-zone.t
Labels: A-TestCase

#1150 Fix queries and response packets content for undelegated tests
  lib/Zonemaster/Engine/Nameserver.pm
Labels: T-Bug

#1158 Update DNSSEC02 implementation
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/profile.json
  t/Test-dnssec.t
Labels: A-TestCase

#1159 Dockerfile: add build dependencies for Net::IP::XS
  Dockerfile
Labels: T-Bug

#1160 Fix Nameserver10 EDNS query
  lib/Zonemaster/Engine/Test/Nameserver.pm
Labels: T-Bug, A-TestCase, P-High

#1161 Zone01: Fix wrong test for localhost IPs
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: T-Bug

#1164 Reinstate DEBUG2 QUERY message tag
  lib/Zonemaster/Engine/Nameserver.pm
  share/profile.json
  t/profiles/Test-all-levels.json
Labels: T-Bug

#1162 use internal ldns for debian/ubuntu
  docs/Installation.md
Labels: A-Documentation, V-Patch

#1163 Fix logic in zone09
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: T-Bug, A-TestCase

#1166 Updates for release v2022.2 (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High
