Repository zonemaster/zonemaster-engine, pull requests merged in 2022-10, with the labels that each got.

#1139 Corrects argument in zone09
  lib/Zonemaster/Engine/Test/Zone.pm
Labels: A-TestCase

#1138 Add logentry arguments for SOA SERIAL
  docs/logentry_args.md
Labels: A-Documentation

#1134 Make root hints configurable, take 2
  .gitignore
  MANIFEST
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Recursor.pm
  lib/Zonemaster/Engine/Util.pm
  share/named.root
  t/util.t
Labels: T-Feature
