Repository zonemaster/zonemaster-engine, pull requests merged in 2022-07, with the labels that each got.

#1083 Updated and added norwegian translation texts
  share/nb.po
Labels: P-High, A-Translation

#1090 #1089 - Fix default value for undelegated tests
  lib/Zonemaster/Engine.pm
Labels: P-High

#1093 Preparation for v2022.1.1 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#1094 Merge develop into master (Engine)
  Changes
  lib/Zonemaster/Engine.pm
  share/da.po
  share/fi.po
  share/nb.po
Labels: P-High

#1072 Editorial update of msgid for DNSSEC01
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-TestCase

#1101 Add check for undelegated test in DNSSEC11
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: T-Bug
