Repository zonemaster/zonemaster-engine, pull requests merged in 2022-05, with the labels that each got.

#1038 Updates the Finnish translation
  share/fi.po
Labels: P-High, A-Translation

#1064 Update message argument document
  docs/logentry_args.md
Labels: A-TestCase, A-Documentation

#1059 Implementation update for DNSSEC01
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/fr.po
  share/profile.json
  t/Test-dnssec.t
Labels: A-TestCase

#1051 Implementation update for DNSSEC02
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  share/profile.json
Labels: T-Bug, A-TestCase

#1066 Include perl-mailtools in Docker image
  Dockerfile
Labels: T-Bug

#1082 Update French translations for release v2022.1
  share/fr.po
Labels: P-High, A-Translation

#1081 Update spanish translation file for upcoming release, ticket #1075
  share/es.po
Labels: P-High, A-Translation

#1073 Updates translation to Swedish (Engine)
  share/sv.po
Labels: P-High, A-Translation
