Repository zonemaster/zonemaster-engine, pull requests merged in 2023-01, with the labels that each got.

#1178 Fix bug in Zone01
  MANIFEST
  lib/Zonemaster/Engine/Constants.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/Zone.pm
  lib/Zonemaster/Engine/Util.pm
  t/Test-zone01-A.data
  t/Test-zone01-A.t
  t/Test-zone01-B.data
  t/Test-zone01-B.t
Labels: T-Bug, A-TestCase, P-High, V-Minor

#1176 Removes libldns3 from list of dependencies
  docs/Installation.md
Labels: A-Documentation

#1177 Update Nameserver11 to check for OPTION-CODE in EDNS response
  lib/Zonemaster/Engine/Test/Nameserver.pm
Labels: T-Bug, A-TestCase, V-Patch

#1181 Fix test issue for Address01
  lib/Zonemaster/Engine/Test/Address.pm
Labels: T-Bug, V-Patch

#1180 Update the Swedish translation (Engine)
  share/sv.po
Labels: A-Translation, V-Patch

#1183 Updates for release v2022.2.1 (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High

#1184 Merge develop into master (Engine)
  Changes
  MANIFEST
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Constants.pm
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Zone.pm
  lib/Zonemaster/Engine/Util.pm
  share/fr.po
  share/sv.po
  t/Test-zone01-A.data
  t/Test-zone01-A.t
  t/Test-zone01-B.data
  t/Test-zone01-B.t
Labels: P-High
