Repository zonemaster/zonemaster-engine, pull requests merged in 2023-07, with the labels that each got.

#1246 Update of the Norwegian translation ref. issue #1228
  share/nb.po
Labels: A-Translation, V-Patch

#1262 Adjusts PO files as a consequence of the update of msgid
  share/da.po
  share/es.po
  share/fi.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: P-High, A-Translation, V-Patch

#1261 Preparation for release v2023.1.1 (Engine)
  Changes
  lib/Zonemaster/Engine.pm
Labels: P-High

#1266 Merge Releases/v2023.1.1 into Master (Engine)
  Changes
  MANIFEST
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/Test.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  share/da.po
  share/es.po
  share/fi.po
  share/fr.po
  share/nb.po
  share/sv.po
  t/Test-basic.data
  t/Test-basic.t
  t/Test-basic02-A.data
  t/Test-basic02-A.t
  t/Test-basic02-B.data
  t/Test-basic02-B.t
  t/zonemaster.data
Labels: P-High
