Repository zonemaster/zonemaster-engine, pull requests merged in 2023-11, with the labels that each got.

#1268 Removes Arguments document moved to the zonemaster/zonemaster respository
  docs/logentry_args.md
Labels: A-Documentation

#1307 Corrects MANIFEST missed in #1268
  MANIFEST
Labels: T-Bug

#1302 Logger refactoring
  lib/Zonemaster/Engine/Logger.pm
  lib/Zonemaster/Engine/Logger/Entry.pm
  lib/Zonemaster/Engine/Test/Address.pm
  lib/Zonemaster/Engine/Test/Basic.pm
  lib/Zonemaster/Engine/Test/Connectivity.pm
  lib/Zonemaster/Engine/Test/Consistency.pm
  lib/Zonemaster/Engine/Test/DNSSEC.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  lib/Zonemaster/Engine/Test/Syntax.pm
  lib/Zonemaster/Engine/Test/Zone.pm
  lib/Zonemaster/Engine/Translator.pm
  t/Test-connectivity.t
  t/Test-consistency.t
  t/Test-dnssec.t
  t/Test-nameserver.t
  t/Test-syntax.t
  t/logger.t
  t/translator.t
Labels: V-Major

#1201 Caching: add global cache based on Redis (experimental)
  MANIFEST
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Nameserver/Cache.pm
  lib/Zonemaster/Engine/Nameserver/Cache/LocalCache.pm
  lib/Zonemaster/Engine/Nameserver/Cache/RedisCache.pm
  lib/Zonemaster/Engine/Profile.pm
  share/profile_additional_properties.json
  t/profiles.t
Labels: V-Minor
