Repository zonemaster/zonemaster-engine, pull requests merged in 2023-05, with the labels that each got.

#1215 Updates unit tests for ZONE09
  MANIFEST
  t/Test-zone09-1.data
  t/Test-zone09-1.t
  t/Test-zone09-A.data
  t/Test-zone09-A.t
  t/Test-zone09-B.data
  t/Test-zone09-B.t
  t/Test-zone09-C.data
  t/Test-zone09-C.t
  t/Test-zone09-D.data
  t/Test-zone09-D.t
  t/Test-zone09-E.data
  t/Test-zone09-E.t
  t/Test-zone09-F.data
  t/Test-zone09-F.t
  t/Test-zone09.data
  t/Test-zone09.t
Labels: A-TestCase, V-Patch

#1216 Updates unit tests for DNSSEC16
  MANIFEST
  t/Test-dnssec.t
  t/Test-dnssec16.data
  t/Test-dnssec16.t
  t/profiles/Test-dnssec16-only.json
Labels: A-TestCase, V-Patch

#1232 Docker: install Locale::PO through CPAN
  Dockerfile
Labels: T-Bug, V-Patch

#1235 Remove documentation (moved to zonemaster/zonemaster)
  MANIFEST
  README.md
  docs/Installation.md
  docs/Profiles.md
Labels: A-Documentation

#1231 Update French translations for v2023.1
  share/fr.po
Labels: A-Translation, V-Patch

#1234 Update spanish translation as requested in issue #1227 (v2)
  share/es.po
Labels: A-Translation, V-Patch
