Repository zonemaster/zonemaster-engine, pull requests merged in 2023-06, with the labels that each got.

#1226 Updates Swedish translation (Engine)
  share/sv.po
Labels: A-Translation, V-Patch

#1237 Updates Danish translation (Engine)
  share/da.po
Labels: A-Translation, V-Patch

#1239 Update French translation of BASIC01 for v2023.1
  share/fr.po
Labels: A-Translation

#1238 Updates translation to Finnish (Engine)
  share/fi.po
Labels: A-Translation, V-Patch

#1241 Preparation for release v2023.1 (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High
