Repository zonemaster/zonemaster-engine, pull requests merged in 2023-02, with the labels that each got.

#1185 Provide a rule `new-po` to create an empty PO file
  share/GNUmakefile
Labels: A-Translation

#1191 Automatically set header fields in new PO files
  share/GNUmakefile
  share/sv.po
Labels: V-Patch

#1202 Deprecate Zonemaster::Engine::Net::IP module
  lib/Zonemaster/Engine/ASNLookup.pm
  lib/Zonemaster/Engine/Constants.pm
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Nameserver/Cache.pm
  lib/Zonemaster/Engine/Net/IP.pm
  lib/Zonemaster/Engine/Profile.pm
  lib/Zonemaster/Engine/Recursor.pm
  lib/Zonemaster/Engine/Test/Delegation.pm
  lib/Zonemaster/Engine/Test/Nameserver.pm
  t/Test-address.t
  t/nameserver.t
  t/recursor.t
Labels: V-Minor

#1196 Update translation to Spanish (Engine) #1188
  share/es.po
Labels: A-Translation, V-Patch

#1199 Updated and added translations. Based on the release-branch-v2022.2.2
  share/nb.po
Labels: A-Translation, V-Patch
