Repository zonemaster/zonemaster-engine, pull requests merged in 2024-03, with the labels that each got.

#1324 Fix typo in Swedish translation of DNSSEC:DNSSEC07
  share/sv.po
Labels: T-Bug, A-Translation

#1327 Fixes a bug in Redis global cache triggered when TTL is 0
  lib/Zonemaster/Engine/Nameserver/Cache/RedisCache.pm
Labels: T-Bug, V-Patch

#1329 Preparation for v2023.2 release (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High
