Repository zonemaster/zonemaster-engine, pull requests merged in 2024-10, with the labels that each got.

#1388 Lowers the levels of ASN related messages from Connectivity03
  share/profile.json
  share/profile.yaml
  t/profiles/Test-all-levels.json
Labels: A-TestCase, V-Minor

#1359 Remove obsolete document
  MANIFEST
  docs/Translation-translators.md
Labels: A-Documentation

#1392 Delegation05: include QNAME and QTYPE in diagnostics for failed queries
  lib/Zonemaster/Engine/Test/Delegation.pm
Labels: V-Patch
