Repository zonemaster/zonemaster-engine, pull requests merged in 2024-07, with the labels that each got.

#1369 Fix regression in Syntax04
  lib/Zonemaster/Engine/Test/Syntax.pm
Labels: T-Bug, V-Patch

#1367 Preparation for release v2024.1 (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High

#1356 Profile fixes
  lib/Zonemaster/Engine/Nameserver/Cache.pm
  lib/Zonemaster/Engine/Profile.pm
  t/profiles.t
Labels: V-Minor
