Repository zonemaster/zonemaster-engine, pull requests merged in 2024-12, with the labels that each got.

#1399 Add Try::Tiny in zonemaster-cli runtime Docker container
  Dockerfile
Labels: T-Bug, P-High, V-Patch

#1402 Fixes unit tests so that they do not leak queries
  t/Test.data
  t/Test.t
Labels: T-Bug, V-Patch

#1410 Preparation for v2024.2 release (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High

#1416 Update Swedish translation
  share/sv.po
  t/po-files.t
Labels: V-Patch
