Repository zonemaster/zonemaster-engine, pull requests merged in 2024-11, with the labels that each got.

#1394 Updates global cache
  lib/Zonemaster/Engine/Nameserver/Cache/RedisCache.pm
  lib/Zonemaster/Engine/Profile.pm
Labels: A-Documentation, V-Minor

#1383 Fix CDS/CDNSKEY RRsets comparison in DNSSEC15
  lib/Zonemaster/Engine/Test/DNSSEC.pm
Labels: A-TestCase, V-Patch

#1352 sort generated data files
  lib/Zonemaster/Engine/Nameserver.pm
Labels: V-Patch

#1398 CI: install ExtUtils::PkgConfig as prerequisite
  .github/workflows/ci.yml
Labels: T-Bug, P-High, V-Patch

#1395 New unit tests for Delegation01, -02 and -03, and legacy tests are removed
  MANIFEST
  t/Test-delegation.t
  t/Test-delegation01-A.data
  t/Test-delegation01-A.t
  t/Test-delegation01-B.data
  t/Test-delegation01-B.t
  t/Test-delegation01-C.data
  t/Test-delegation01-C.t
  t/Test-delegation01-D.data
  t/Test-delegation01-D.t
  t/Test-delegation01-E.data
  t/Test-delegation01-E.t
  t/Test-delegation01-F.data
  t/Test-delegation01-F.t
  t/Test-delegation01-G.data
  t/Test-delegation01-G.t
  t/Test-delegation01-H.data
  t/Test-delegation01-H.t
  t/Test-delegation01-I.data
  t/Test-delegation01-I.t
  t/Test-delegation01-J.data
  t/Test-delegation01-J.t
  t/Test-delegation01-K.data
  t/Test-delegation01-K.t
  t/Test-delegation01-L.data
  t/Test-delegation01-L.t
  t/Test-delegation01-M.data
  t/Test-delegation01-M.t
  t/Test-delegation01.data
  t/Test-delegation01.t
  t/Test-delegation02-A.data
  t/Test-delegation02-A.t
  t/Test-delegation02-B.data
  t/Test-delegation02-B.t
  t/Test-delegation02-C.data
  t/Test-delegation02-C.t
  t/Test-delegation02-D.data
  t/Test-delegation02-D.t
  t/Test-delegation02.data
  t/Test-delegation02.t
  t/Test-delegation03-A.data
  t/Test-delegation03-A.t
  t/Test-delegation03-B.data
  t/Test-delegation03-B.t
  t/Test-delegation03-C.data
  t/Test-delegation03-C.t
  t/Test-delegation03.data
  t/Test-delegation03.t
Labels: V-Patch
