Repository zonemaster/zonemaster-engine, pull requests merged in 2025-06, with the labels that each got.

#1420 Improve performance by optimizing critical code sections
  lib/Zonemaster/Engine.pm
  lib/Zonemaster/Engine/DNSName.pm
  lib/Zonemaster/Engine/Nameserver.pm
  lib/Zonemaster/Engine/Packet.pm
  lib/Zonemaster/Engine/TestMethodsV2.pm
  lib/Zonemaster/Engine/Util.pm
Labels: V-Major

#1460 Update Dockerfile for release 2025.1
  Dockerfile
Labels: P-High

#1418 Danish translation (engine)
  share/da.po
Labels: A-Translation, V-Patch

#1461 Preparation for v2025.1 release (Engine)
  Changes
  Makefile.PL
  lib/Zonemaster/Engine.pm
Labels: P-High
