Repository zonemaster/zonemaster-engine, pull requests merged in 2025-05, with the labels that each got.

#1450 Editoral update of unit test file for Connectivity04
  t/Test-connectivity04-A.t
Labels: A-Documentation, V-Patch

#1452 DNSSEC03: downgrade from ERROR to WARNING
  share/profile.json
  share/profile.yaml
Labels: A-TestCase, V-Patch

#1432 Fix alias (CNAME) handling in Address03 test case
  MANIFEST
  lib/Zonemaster/Engine/Test/Address.pm
  t/Test-address.t
  t/Test-address03.data
  t/Test-address03.t
Labels: A-TestCase, V-Patch

#1455 Lower all WARNING to NOTICE for Zone01 in profile
  share/profile.json
  share/profile.yaml
Labels: A-TestCase, V-Minor
